services:
 - type: worker
   name: tracertech-md-demo
   env: docker
   plan: free
   dockerfilePath: ./Dockerfile
   envVars:
    - key: SESSION_ID
      value: Session~
    - key: BOT_INFO
      value: ï¼”ï½ï¼¦à¹›Trappy;ğšƒğšğ™°ğ™²ğ™´ğšğšƒğ™´ğ™²ğ™·-ğ™¼ğ™³
    - key: SUDO
      value: 254727472670
    - key: ANTILINK
      value: "true"
